- name: Install required APT packages
  become: true
  apt:
    update_cache: yes
    name:
      - stunnel4
      - haproxy
      - traceroute
      - curl
      - build-essential
      - libssl-dev
      - libffi-dev
      - python3-dev
      - python3-venv
      - sshfs
      - coreutils
      - autoconf
      - automake
      - libtool
      - pkg-config
      - ca-certificates
      - gnupg
      - lsb-release
      - net-tools
      - libsctp1
      - netcat-openbsd
      - moreutils
      - iftop
      - bmon
      - nethogs
      - nginx
      - libcap2-bin
    state: present
