- name: Pre-accept tshark debconf
  become: true
  debconf:
    name: wireshark-common
    question: wireshark-common/install-setuid
    value: true
    vtype: boolean

- name: Install tshark
  become: true
  apt:
    name: tshark
    state: present

- name: Add user to wireshark group
  become: true
  user:
    name: "{{ ansible_user_id }}"
    groups: wireshark
    append: yes
